version: "3.8"

services:
  app:
    container_name: scriptcreador1
    image: scriptcreador1
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000